version: '3'
services:
  main-service:
    build: ./services/main_service
    image: main-service:latest
    ports:
      - "8000:8000"
    depends_on:
      - finance-service
  finance-service:
    build: ./services/finance_service
    image: finance-service:latest
    ports:
      - "8003:8003"
    volumes:
      - ./services/finance_service/persistent:/finance_service/persistent