version: '3.8'
services:
  main-service:
    image: main-service:latest
    ports:
      - "8000:8000"
    command: pytest
    depends_on:
      - finance-service
  finance-service:
    image: finance-service:latest
    ports:
      - "8003:8003"