version: '3.8'

services:
  nginx:
    image: nginx:1.21-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - main-service
    restart: always
    networks:
      - mortgage-network
    environment:
      - DOMAIN=${DOMAIN:-139-162-198-94.ip.linodeusercontent.com}

  main-service:
    image: dmwa14/mortgage-main-service:${VERSION}
    expose:
      - "8000"  # Only expose to internal network, not to host
    restart: always
    depends_on:
      - finance-service
    networks:
      - mortgage-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  finance-service:
    image: dmwa14/mortgage-finance-service:${VERSION}
    expose:
      - "8003"  # Only exposed internally
    restart: always
    networks:
      - mortgage-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  mortgage-network:
    driver: bridge 